### ISSUE TITLE
About references nonexistent sidebar

### ISSUE THREAD

**Issue by Shriken** [Team694/team694.github.io#114]
The [About this Website page](https://github.com/Team694/team694.github.io/blob/master/about/website/index.md) says
"Check out the sidebar for links to other sites in the StuyPulse Network", but there is no sidebar.

**Comment by kevinwang** [comment]
Probably have to remove the `index.html` from string comparisons in https://github.com/Team694/team694.github.io/blob/master/_layouts/page-with-sidebar.html

**Comment by Shriken** [comment]
@kevinwang tending to his baby from beyond the graduation

**Comment by kevinwang** [comment]
I could say the same about you!

**Comment by Shriken** [comment]
Heheh, true.
I'm building my own website <https://zanesterling.io>, so I wanted a good
link to StuyPulse.

**Comment by justinkim** [comment]
Increíble. The man is swift.
