### ISSUE TITLE
Outdated "Divisions" page

### ISSUE THREAD

**Issue by WilsonBerkow** [Team694/team694.github.io#115]
By the Charter we are departments, not divisions. The [Divisions](https://stuypulse.com/about/divisions/) page should be updated accordingly.

Also some of the content is dated (e.g. "Engineering is by far the largest of the divisions").

I think @justinkim will be interested in this.

**Comment by justinkim** [comment]
Needs an assignee. @WilsonBerkow

**Comment by WilsonBerkow** [comment]
My bad.

**Comment by james9909** [comment]
The term "division" has been replaced with "department", and I worked with Yedoh to update the  descriptions and photos on the page.

**Comment by justinkim** [comment]
Reference issue numbers in your PR please. When you do, it shows up in the issue feed so future readers can see how you fixed it.
