### ISSUE TITLE
Some logos on the sponsor page do not appear

### ISSUE THREAD

**Issue by dannyqiu** [Team694/team694.github.io#51]
The Bloomberg logo is out of place, it may be a problem with the for loops used to create the layout.
EDIT: It seems to be that the sponsors without a logo (all sponsors after SHS Parent's Association) aren't showing, making the Bloomberg logo look out of place.

![Bloomberg Logo](https://f.cloud.github.com/assets/1170755/576957/a9d907ca-c81c-11e2-9bf6-88ea4853ee86.png)

**Comment by kevinwang** [comment]
Reopening as Adblock Plus blocks the class `.sponsor-logo`.

![](http://f.kev.wang/i/S1odeQ.png)

**Comment by james9909** [comment]
Fixed in #104.
